apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secrets.name_prefix | default "audio-system" | trunc 63 | lower }}-db
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.secrets.db_username_secret }}
        objectType: secretsmanager
      - objectName: {{ .Values.secrets.db_password_secret }}
        objectType: secretsmanager
  secretObjects:
    - secretName: db-credentials
      type: Opaque
      data:
        - objectName: {{ .Values.secrets.db_username_secret }}
          key: DB_USERNAME
        - objectName: {{ .Values.secrets.db_password_secret }}
          key: DB_PASSWORD
