apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secrets.name_prefix }}-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.secrets.db_username_secret | default "" }}
        objectType: secretsmanager
      - objectName: {{ .Values.secrets.db_password_secret | default "" }}
        objectType: secretsmanager
      - objectName: {{ .Values.secrets.rabbit_user_secret | default "" }}
        objectType: secretsmanager
      - objectName: {{ .Values.secrets.rabbit_pass_secret | default "" }}
        objectType: secretsmanager
